export const AssetList = [
  {
    token: "Ethereum XEQ",
    ticker: "wXEQ",
    price: "$0.00",
    change: "~ 0.00",
    symbol: "$",
  },
  {
    token: "Binance Smart Chain XEQ",
    ticker: "bXEQ",
    price: "$0.00",
    change: "~ 0.00",
    symbol: "$",
  },
  {
    token: "Polkadot XEQ",
    ticker: "pXEQ",
    price: "$0.00",
    change: "~ 0.00",
    symbol: "$",
  },

  {
    token: "Cardano XEQ",
    ticker: "cXEQ",
    price: "$0.00",
    change: "~ 0.00",
    symbol: "$",
  },
  // {
  //   token: "Silver",
  //   ticker: "SILV",
  //   price: "$1.00",
  //   change: "~ 0.00",
  //   symbol: "$",
  // },
];

// {
//   token: "Bitcoin",
//   ticker: "BTC",
//   price: "$1.00",
//   change: "~ 0.00",
//   symbol: "$",
// },
// {
//   token: "Swiss Franc",
//   ticker: "CHF",
//   price: "$1.00",
//   change: "~ 0.00",
//   symbol: "₣",
// },
// {
//   token: "Canadian Dollar",
//   ticker: "CAD",
//   price: "$1.00",
//   change: "~ 0.00",
//   symbol: "$",
// },
//
// {
//   token: "Australian Dollar",
//   ticker: "AUD",
//   price: "$1.00",
//   change: "~ 0.00",
//   symbol: "$",
// },
// {
//   token: "New Zealand Dollar",
//   ticker: "NZD",
//   price: "$1.00",
//   change: "~ 0.00",
//   symbol: "$",
// },
// {
//   token: "Norwegian Krone",
//   ticker: "NOK",
//   price: "$1.00",
//   change: "~ 0.00",
//   symbol: "kr",
// },
// {
//   token: "Japanese Yen",
//   ticker: "JPY",
//   price: "$1.00",
//   change: "~ 0.00",
//   symbol: "¥",
// },
// {
//   token: "British Pound",
//   ticker: "GBP",
//   price: "$1.00",
//   change: "~ 0.00",
//   symbol: "£",
// },
